name: "Publish a flake to flakestry"
on:
    push:
        branches:
          - main
jobs:
    publish-flake:
        runs-on: ubuntu-latest
        permissions:
            id-token: "write"
            contents: "read"
        steps:
            - uses: flakestry/flakestry-publish@pull/6/head
              with:
                ref: "${{ github.ref_name }}"
                version: "v0.0.0"
                ignoreConflicts: true
